## Configuracion de Spring
spring:
  application:
    name: ms-inventory-products

## Configuracion de Instancia 
server:
  port: ${PORT:8088}
  fullAddress: ${HOST:http://localhost:${server.port}}

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
    hostname: ${HOSTNAME:ms-inventory-products}
    non-secure-port-enabled: false
    secure-port-enabled: true
    non-secure-port: 80
    secure-port: 443

##Elasticsearch config
elasticsearch:
  host: ${ELASTICSEARCH_HOST:dwisearch-2706410038.us-east-1.bonsaisearch.net}
  credentials:
    user: ${ELASTICSEARCH_USER:eqmv6djf9z}
    password: ${ELASTICSEARCH_PWD:dqedcjgvgy}
logging:
  level:
    tracer: TRACE